In [107]:
#import libraries
import numpy as np
import pandas as pd

In [108]:
#read daataset
dataset=pd.read_csv('bank.csv')

In [109]:
dataset.head(10)

age         job   marital  education default  balance housing loan  \
0   59      admin.   married  secondary      no     2343     yes   no   
1   56      admin.   married  secondary      no       45      no   no   
2   41  technician   married  secondary      no     1270     yes   no   
3   55    services   married  secondary      no     2476     yes   no   
4   54      admin.   married   tertiary      no      184      no   no   
5   42  management    single   tertiary      no        0     yes  yes   
6   56  management   married   tertiary      no      830     yes  yes   
7   60     retired  divorced  secondary      no      545     yes   no   
8   37  technician   married  secondary      no        1     yes   no   
9   28    services    single  secondary      no     5090     yes   no   

   contact  day month  duration  campaign  pdays  previous poutcome deposit  
0  unknown    5   may      1042         1     -1         0  unknown     yes  
1  unknown    5   may      1467         1     -1         0  unknown     yes  
2  unknown    5   may      1389         1     -1         0  unknown     yes  
3  unknown    5   may       579         1     -1         0  unknown     yes  
4  unknown    5   may       673         2     -1         0  unknown     yes  
5  unknown    5   may       562         2     -1         0  unknown     yes  
6  unknown    6   may      1201         1     -1         0  unknown     yes  
7  unknown    6   may      1030         1     -1         0  unknown     yes  
8  unknown    6   may       608         1     -1         0  unknown     yes  
9  unknown    6   may      1297         3     -1         0  unknown     yes

In [110]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [111]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
age          11162 non-null int64
job          11162 non-null object
marital      11162 non-null object
education    11162 non-null object
default      11162 non-null object
balance      11162 non-null int64
housing      11162 non-null object
loan         11162 non-null object
contact      11162 non-null object
day          11162 non-null int64
month        11162 non-null object
duration     11162 non-null int64
campaign     11162 non-null int64
pdays        11162 non-null int64
previous     11162 non-null int64
poutcome     11162 non-null object
deposit      11162 non-null object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [112]:
x = dataset.iloc[:,0:16].values
y = dataset.iloc[:,16:17].values

In [113]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [114]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [115]:
x.shape

(11162, 16)

In [116]:
y.shape

(11162, 1)

In [117]:
dataset["job"].unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [118]:
dataset["marital"].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [119]:
dataset["education"].unique()

array(['secondary', 'tertiary', 'primary', 'unknown'], dtype=object)

In [120]:
dataset["default"].unique()


array(['no', 'yes'], dtype=object)

In [121]:
dataset["housing"].unique()


array(['yes', 'no'], dtype=object)

In [122]:
dataset["loan"].unique()

array(['no', 'yes'], dtype=object)

In [123]:
dataset["contact"].unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [124]:
dataset["month"].unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [125]:
dataset["poutcome"].unique()

array(['unknown', 'other', 'failure', 'success'], dtype=object)

In [126]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


In [127]:
ct = ColumnTransformer([('one', OneHotEncoder(), [1,2,3,4,6,7,8,10,15])], remainder = 'passthrough')
x= ct.fit_transform(x)


In [128]:
x.shape

(11162, 51)

In [129]:
ct1 = ColumnTransformer([('one', OneHotEncoder(), [0])], remainder = 'passthrough')
y= ct1.fit_transform(y)

In [130]:
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [131]:
y.shape

(11162, 2)

In [132]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2,random_state = 0)

In [133]:
print('x shape ', x.shape)
print('y shape ', y.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

x shape  (11162, 51)
y shape  (11162, 2)
x_train shape  (8929, 51)
x_test shape  (2233, 51)
y_train shape  (8929, 2)
y_test shape (2233, 2)


In [134]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [135]:
x_train[0:2,:]

array([[-0.37172192, -0.45760242, -0.17658264, -0.1589378 ,  1.8452729 ,
        -0.27363591, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772, -0.36485864,  0.86351031, -0.66975544,
        -0.39346051,  1.01614555, -0.69993206, -0.21741017,  0.12621015,
        -0.12621015, -1.05825117,  1.05825117,  0.39003722, -0.39003722,
        -1.60273048, -0.27292594,  1.93439945, -0.30193478, -0.39913565,
        -0.09686471, -0.27410848, -0.17488949, -0.39459853, -0.34910544,
        -0.15930776,  1.70870313, -0.30215554, -0.1931085 , -0.16761389,
        -0.35031555, -0.22657536, -0.32939951,  0.58661881,  0.64941897,
        -0.44565283, -0.90504798, -0.2483547 , -0.56394809, -0.48428507,
        -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, -0.1589378 , -0.54192526,
         3.65449114, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772,  2.7407875 , -1.15806377, -0.66975544,
        -0.39346051,  1.01614

In [136]:
x_train.shape

(8929, 51)

In [137]:
y_train.shape

(8929, 2)

In [138]:
#  initializes the model
from tensorflow.keras.models import Sequential 
#this import statement is to add layers
from tensorflow.keras.layers import Dense

In [139]:
# adding input layer
classification=Sequential()

In [140]:
#adding hidden layer
classification.add(Dense(units=51,kernel_initializer='random_uniform',activation='relu'))

In [141]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [142]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [143]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [144]:
classification.add(Dense(units=102,kernel_initializer='random_uniform',activation='relu'))

In [145]:
#adding output layer
classification.add(Dense(units=2,kernel_initializer='random_uniform',activation='softmax'))

In [146]:
classification.compile(optimizer = "adam",loss = "categorical_crossentropy",metrics = ["accuracy"])

In [147]:
#train the model
classification.fit(x_train,y_train, epochs = 40)

Epoch 1/40
8929/8929 [==============================] - 0s 53us/sample - loss: 0.4415 - acc: 0.8003
Epoch 2/40
8929/8929 [==============================] - 0s 33us/sample - loss: 0.3617 - acc: 0.8490
Epoch 3/40
8929/8929 [==============================] - 0s 33us/sample - loss: 0.3507 - acc: 0.8542
Epoch 4/40
8929/8929 [==============================] - 0s 33us/sample - loss: 0.3365 - acc: 0.8614
Epoch 5/40
8929/8929 [==============================] - 0s 33us/sample - loss: 0.3270 - acc: 0.8629
Epoch 6/40
8929/8929 [==============================] - 0s 33us/sample - loss: 0.3216 - acc: 0.8680
Epoch 7/40
8929/8929 [==============================] - 0s 33us/sample - loss: 0.3116 - acc: 0.8736
Epoch 8/40
8929/8929 [==============================] - 0s 34us/sample - loss: 0.3078 - acc: 0.8733
Epoch 9/40
8929/8929 [==============================] - 0s 33us/sample - loss: 0.3004 - acc: 0.8775
Epoch 10/40
8929/8929 [==============================] - 0s 33us/sample - loss: 0.2968 - acc: 0.8792

In [148]:
ypred = classification.predict(x_test)

In [149]:
ypred

array([[1.00000000e+00, 6.62408818e-15],
       [1.01537262e-05, 9.99989867e-01],
       [1.00000000e+00, 1.02227303e-10],
       ...,
       [1.06135849e-02, 9.89386439e-01],
       [9.99987006e-01, 1.29420814e-05],
       [8.89752030e-01, 1.10247955e-01]], dtype=float32)

In [150]:
ypred = ypred >0.5

In [151]:
ypred

array([[ True, False],
       [False,  True],
       [ True, False],
       ...,
       [False,  True],
       [ True, False],
       [ True, False]])

In [152]:
y_test

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])

In [153]:
dataset.head(2)

age     job  marital  education default  balance housing loan  contact  \
0   59  admin.  married  secondary      no     2343     yes   no  unknown   
1   56  admin.  married  secondary      no       45      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes

In [154]:
yp=classification.predict(sc.transform(ct.transform([[59,'admin.','married','secondary','no',2343,'yes','no','unknown',5,'may',1042,1,-1,0,'unknown']])))

In [156]:
deposit = ["no","yes"]
prediction = deposit[np.argmax(yp)]

In [157]:
#predict the result
prediction

'yes'